/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include third party header files ----------------

#include "distortion.h"
#include "pitchShift.h"
#include "reverb.h"

// Include compiled network files ------------------

#include "distorion.h"
#include "script_fx1.h"
#include "script_fx2.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

